version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "3001:5432"
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: UserDB
    container_name: new_container_userdb
    volumes:
      - ./postgres:/var/lib/postgresql/data