version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "7005:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: userdb_development
    volumes:
      - ./postgres:/var/lib/postgresql/data