version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: UserDB
    container_name: new_container_userdb
    volumes:
      - db_data_locally:/var/lib/postgresql/data

volumes:
  db_data_locally: