version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .docker/dockerfile
    environment:
      - PORT=3000
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=myusername
      - DB_PASSWORD=mypassword
      - DB_DATABASE=UserDB

  nginx:  
    image: nginx:latest  
    ports:
      - "3000:80"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/conf.d/default.conf:ro
    command: /bin/bash -c "nginx -g 'daemon off;'"

  postgresql:
    image: postgres:14.3
    ports:
      - "3001:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgresql-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: UserDB
    container_name: userdb_docker

volumes:
  db_data: